### ISSUE TITLE
Authentication basic story

### ISSUE THREAD

**Issue by inercia** [datawire/kubecon-19-demo#25]
## User story

* A page shows something (an animated Halloween pumpkin?) and it's not authenticated
* Then we apply the authentication YAML and refresh
* The same page now requires authentication.

The left YAML we have at the left should be removed. That seems to be defining the page? But aren't we already looking at the page? So isn't it already defined? I find it just confusing.

**Comment by containscafeine** [comment]
Fixed in #35
