### ISSUE TITLE
Rebrand the UI

### ISSUE THREAD

**Issue by inercia** [datawire/kubecon-19-demo#4]
## Description

We must refresh the UI.

## Use case

The chart page needs to be styled and look nicer. It needs to have the Datawire and Ambassador Edge Stack branding. It needs to say something like "Rate Limiting in Action", etc. (In the video it's a docs page which doesn't have "booth sized/style" branding: big, simple, etc.)

**Comment by containscafeine** [comment]
Closed in #12
